### ISSUE TITLE
Only take action when server is almost full

### ISSUE THREAD

**Issue by Apecengo** [LapisPlugins/AFKPlus#11]
This is a feature suggestion.

As a server admin, I would like to allow players to be AFK, but only as long as the server is not full, or almost full. 

How it could work:

By adding a new permission config called MinPlayersToAction, that takes an int. For that permission level, as long as there are less players than the amount set, the system won't trigger any actions. (0 means always take action)

For example: (see last option)

```yaml
Permissions:
  afkplus,player:
    #Who should get this permission without it being given, 0 = no one, 1 = everyone, 2 = Ops
    Default: 1
    #If a player has more than 1 permission they will be given the one with the highest priority
    Priority: 1
    #Can the player set themselves as AFK with the /afk command
    AFKSelf: 1
    #Can the player set others as AFK with the /afk command
    AFKOthers: 0
    #How many seconds of inactivity are required before they will automatically be set as AFK
    #Set to -1 if the player shouldn't be automatically placed in AFK
    TimeToAFK: 30
    #How many seconds of AFK are required before the player is warned about action being taken
    #Set to -1 to disable warnings for this permission
    TimeToWarning: 90
    #How many seconds of AFK are required before the player is acted upon
    #Set to -1 to disable actions for this permission
    TimeToAction: 120
    #Can this player use the update command to install new versions
    CanUpdate: 0
    #How many players have to be on for the plugin to take action? Useful to not kick players if
    # the server is not full (set to 0 to always take action)
    MinPlayersToAction: 23 
```

I think this might be relatively easy to implement, I've tried to do it myself but I can't compile the project locally:

```
[ERROR] Failed to execute goal on project AFKPlus: Could not resolve dependencies for project net.lapismc:AFKPlus:jar:3.2.0: Failure to find net.lapismc:LapisCore:jar:1.7.8 in https://hub.spigotmc.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of spigotmc-repo has elapsed or updates are forced -> [Help 1]
```

Thanks!
